image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: "Deploy to Develop"
          image: node:14.17.0
          deployment: develop
          script:
            - npm install
            - npm run build
